In [1]:
import pandas as pd
df=pd.read_csv("titanic.csv")

In [2]:
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Embarked"],axis=1,inplace=True)

In [4]:
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [5]:
target=df.Survived
inputs=df.drop("Survived",axis=1)

In [6]:
dummies=pd.get_dummies(inputs.Sex)

In [7]:
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [8]:
inputs=pd.concat([inputs,dummies],axis=1)
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [9]:
inputs.drop("Sex",axis=1,inplace=True)

In [10]:
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [11]:
 inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [12]:
inputs.Age.mean()

29.69911764705882

In [13]:
inputs=inputs.Age.fillna(inputs.Age.mean())
inputs = inputs.values

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test=train_test_split(inputs,target,test_size=0.2)
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

In [16]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [17]:
model.fit(X_train,y_train)

GaussianNB()

In [18]:
model.score(X_test,y_test)

0.6312849162011173

In [19]:
X_test[:10]

array([[29.69911765],
       [27.        ],
       [29.69911765],
       [60.        ],
       [25.        ],
       [26.        ],
       [20.        ],
       [56.        ],
       [56.        ],
       [52.        ]])

In [20]:
y_test[:10]

524    0
216    1
468    0
587    1
271    1
69     0
131    0
879    1
647    1
262    0
Name: Survived, dtype: int64

In [21]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
model.predict_proba(X_test[:10])

array([[0.64533693, 0.35466307],
       [0.6382957 , 0.3617043 ],
       [0.64533693, 0.35466307],
       [0.5538774 , 0.4461226 ],
       [0.63145269, 0.36854731],
       [0.63504932, 0.36495068],
       [0.6080771 , 0.3919229 ],
       [0.58496897, 0.41503103],
       [0.58496897, 0.41503103],
       [0.60988392, 0.39011608]])